INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_COLLAR_DETECT collar_detect)

FIND_PATH(
    COLLAR_DETECT_INCLUDE_DIRS
    NAMES collar_detect/api.h
    HINTS $ENV{COLLAR_DETECT_DIR}/include
        ${PC_COLLAR_DETECT_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    COLLAR_DETECT_LIBRARIES
    NAMES gnuradio-collar_detect
    HINTS $ENV{COLLAR_DETECT_DIR}/lib
        ${PC_COLLAR_DETECT_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(COLLAR_DETECT DEFAULT_MSG COLLAR_DETECT_LIBRARIES COLLAR_DETECT_INCLUDE_DIRS)
MARK_AS_ADVANCED(COLLAR_DETECT_LIBRARIES COLLAR_DETECT_INCLUDE_DIRS)

