# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1224, 770)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralWidgetLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.centralWidgetLayout.setObjectName("centralWidgetLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.leftFrame = QtWidgets.QFrame(self.centralwidget)
        self.leftFrame.setMaximumSize(QtCore.QSize(400, 16777215))
        self.leftFrame.setAutoFillBackground(False)
        self.leftFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftFrame.setObjectName("leftFrame")
        self.leftLayout = QtWidgets.QVBoxLayout(self.leftFrame)
        self.leftLayout.setContentsMargins(4, 4, 4, 4)
        self.leftLayout.setObjectName("leftLayout")
        self.receiverLayout = QtWidgets.QVBoxLayout()
        self.receiverLayout.setContentsMargins(-1, 0, -1, -1)
        self.receiverLayout.setSpacing(1)
        self.receiverLayout.setObjectName("receiverLayout")
        self.freqLayout = QtWidgets.QHBoxLayout()
        self.freqLayout.setObjectName("freqLayout")
        self.freqLbl = QtWidgets.QLabel(self.leftFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freqLbl.sizePolicy().hasHeightForWidth())
        self.freqLbl.setSizePolicy(sizePolicy)
        self.freqLbl.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.freqLbl.setFont(font)
        self.freqLbl.setObjectName("freqLbl")
        self.freqLayout.addWidget(self.freqLbl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.freqLayout.addItem(spacerItem)
        self.freqVal = QtWidgets.QLineEdit(self.leftFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freqVal.sizePolicy().hasHeightForWidth())
        self.freqVal.setSizePolicy(sizePolicy)
        self.freqVal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.freqVal.setAlignment(QtCore.Qt.AlignCenter)
        self.freqVal.setReadOnly(True)
        self.freqVal.setObjectName("freqVal")
        self.freqLayout.addWidget(self.freqVal)
        self.freqUnit = QtWidgets.QLabel(self.leftFrame)
        self.freqUnit.setMinimumSize(QtCore.QSize(35, 0))
        self.freqUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.freqUnit.setObjectName("freqUnit")
        self.freqLayout.addWidget(self.freqUnit)
        self.freqStacked = QtWidgets.QStackedWidget(self.leftFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freqStacked.sizePolicy().hasHeightForWidth())
        self.freqStacked.setSizePolicy(sizePolicy)
        self.freqStacked.setMaximumSize(QtCore.QSize(60, 16777215))
        self.freqStacked.setObjectName("freqStacked")
        self.freqCog = QtWidgets.QWidget()
        self.freqCog.setObjectName("freqCog")
        self.freqCogLayout = QtWidgets.QHBoxLayout(self.freqCog)
        self.freqCogLayout.setObjectName("freqCogLayout")
        self.freqBtn = QtWidgets.QPushButton(self.freqCog)
        self.freqBtn.setMinimumSize(QtCore.QSize(10, 10))
        self.freqBtn.setMaximumSize(QtCore.QSize(75, 16777215))
        self.freqBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/Icons/cog_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.freqBtn.setIcon(icon)
        self.freqBtn.setIconSize(QtCore.QSize(24, 24))
        self.freqBtn.setObjectName("freqBtn")
        self.freqCogLayout.addWidget(self.freqBtn)
        self.freqStacked.addWidget(self.freqCog)
        self.freqOkCancel = QtWidgets.QWidget()
        self.freqOkCancel.setObjectName("freqOkCancel")
        self.freqOkCancelLayout = QtWidgets.QHBoxLayout(self.freqOkCancel)
        self.freqOkCancelLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.freqOkCancelLayout.setContentsMargins(0, 0, 0, 0)
        self.freqOkCancelLayout.setSpacing(0)
        self.freqOkCancelLayout.setObjectName("freqOkCancelLayout")
        self.freqOkBtn = QtWidgets.QPushButton(self.freqOkCancel)
        self.freqOkBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Assets/Icons/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.freqOkBtn.setIcon(icon1)
        self.freqOkBtn.setObjectName("freqOkBtn")
        self.freqOkCancelLayout.addWidget(self.freqOkBtn)
        self.freqCancelBtn = QtWidgets.QPushButton(self.freqOkCancel)
        self.freqCancelBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Assets/Icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.freqCancelBtn.setIcon(icon2)
        self.freqCancelBtn.setObjectName("freqCancelBtn")
        self.freqOkCancelLayout.addWidget(self.freqCancelBtn)
        self.freqStacked.addWidget(self.freqOkCancel)
        self.freqLayout.addWidget(self.freqStacked)
        self.receiverLayout.addLayout(self.freqLayout)
        self.snrLayout = QtWidgets.QHBoxLayout()
        self.snrLayout.setObjectName("snrLayout")
        self.snrLbl = QtWidgets.QLabel(self.leftFrame)
        self.snrLbl.setMinimumSize(QtCore.QSize(130, 40))
        self.snrLbl.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.snrLbl.setFont(font)
        self.snrLbl.setObjectName("snrLbl")
        self.snrLayout.addWidget(self.snrLbl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.snrLayout.addItem(spacerItem1)
        self.snrVal = QtWidgets.QLineEdit(self.leftFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snrVal.sizePolicy().hasHeightForWidth())
        self.snrVal.setSizePolicy(sizePolicy)
        self.snrVal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.snrVal.setAlignment(QtCore.Qt.AlignCenter)
        self.snrVal.setReadOnly(True)
        self.snrVal.setObjectName("snrVal")
        self.snrLayout.addWidget(self.snrVal)
        self.snrUnit = QtWidgets.QLabel(self.leftFrame)
        self.snrUnit.setMinimumSize(QtCore.QSize(35, 0))
        self.snrUnit.setText("")
        self.snrUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.snrUnit.setObjectName("snrUnit")
        self.snrLayout.addWidget(self.snrUnit)
        self.snrStacked = QtWidgets.QStackedWidget(self.leftFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snrStacked.sizePolicy().hasHeightForWidth())
        self.snrStacked.setSizePolicy(sizePolicy)
        self.snrStacked.setMaximumSize(QtCore.QSize(60, 16777215))
        self.snrStacked.setObjectName("snrStacked")
        self.snrCog = QtWidgets.QWidget()
        self.snrCog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.snrCog.setObjectName("snrCog")
        self.snrCogLayout = QtWidgets.QHBoxLayout(self.snrCog)
        self.snrCogLayout.setObjectName("snrCogLayout")
        self.snrBtn = QtWidgets.QPushButton(self.snrCog)
        self.snrBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snrBtn.sizePolicy().hasHeightForWidth())
        self.snrBtn.setSizePolicy(sizePolicy)
        self.snrBtn.setMinimumSize(QtCore.QSize(10, 10))
        self.snrBtn.setMaximumSize(QtCore.QSize(75, 16777215))
        self.snrBtn.setText("")
        self.snrBtn.setIcon(icon)
        self.snrBtn.setIconSize(QtCore.QSize(24, 24))
        self.snrBtn.setObjectName("snrBtn")
        self.snrCogLayout.addWidget(self.snrBtn)
        self.snrStacked.addWidget(self.snrCog)
        self.snrOkCancel = QtWidgets.QWidget()
        self.snrOkCancel.setObjectName("snrOkCancel")
        self.snrOkCancelLayout = QtWidgets.QHBoxLayout(self.snrOkCancel)
        self.snrOkCancelLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.snrOkCancelLayout.setContentsMargins(0, 0, 0, 0)
        self.snrOkCancelLayout.setSpacing(0)
        self.snrOkCancelLayout.setObjectName("snrOkCancelLayout")
        self.snrOkBtn = QtWidgets.QPushButton(self.snrOkCancel)
        self.snrOkBtn.setText("")
        self.snrOkBtn.setIcon(icon1)
        self.snrOkBtn.setObjectName("snrOkBtn")
        self.snrOkCancelLayout.addWidget(self.snrOkBtn)
        self.snrCancelBtn = QtWidgets.QPushButton(self.snrOkCancel)
        self.snrCancelBtn.setText("")
        self.snrCancelBtn.setIcon(icon2)
        self.snrCancelBtn.setObjectName("snrCancelBtn")
        self.snrOkCancelLayout.addWidget(self.snrCancelBtn)
        self.snrStacked.addWidget(self.snrOkCancel)
        self.snrLayout.addWidget(self.snrStacked)
        self.receiverLayout.addLayout(self.snrLayout)
        self.gainLayout = QtWidgets.QHBoxLayout()
        self.gainLayout.setObjectName("gainLayout")
        self.gainLbl = QtWidgets.QLabel(self.leftFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainLbl.sizePolicy().hasHeightForWidth())
        self.gainLbl.setSizePolicy(sizePolicy)
        self.gainLbl.setMinimumSize(QtCore.QSize(130, 40))
        self.gainLbl.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.gainLbl.setFont(font)
        self.gainLbl.setObjectName("gainLbl")
        self.gainLayout.addWidget(self.gainLbl)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gainLayout.addItem(spacerItem2)
        self.gainVal = QtWidgets.QLineEdit(self.leftFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainVal.sizePolicy().hasHeightForWidth())
        self.gainVal.setSizePolicy(sizePolicy)
        self.gainVal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gainVal.setAlignment(QtCore.Qt.AlignCenter)
        self.gainVal.setReadOnly(True)
        self.gainVal.setObjectName("gainVal")
        self.gainLayout.addWidget(self.gainVal)
        self.gainUnit = QtWidgets.QLabel(self.leftFrame)
        self.gainUnit.setMinimumSize(QtCore.QSize(35, 0))
        self.gainUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.gainUnit.setObjectName("gainUnit")
        self.gainLayout.addWidget(self.gainUnit)
        self.gainStacked = QtWidgets.QStackedWidget(self.leftFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainStacked.sizePolicy().hasHeightForWidth())
        self.gainStacked.setSizePolicy(sizePolicy)
        self.gainStacked.setMaximumSize(QtCore.QSize(60, 16777215))
        self.gainStacked.setObjectName("gainStacked")
        self.gainCog = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainCog.sizePolicy().hasHeightForWidth())
        self.gainCog.setSizePolicy(sizePolicy)
        self.gainCog.setObjectName("gainCog")
        self.gainCogLayout = QtWidgets.QVBoxLayout(self.gainCog)
        self.gainCogLayout.setObjectName("gainCogLayout")
        self.gainBtn = QtWidgets.QPushButton(self.gainCog)
        self.gainBtn.setMinimumSize(QtCore.QSize(10, 10))
        self.gainBtn.setMaximumSize(QtCore.QSize(75, 16777215))
        self.gainBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gainBtn.setText("")
        self.gainBtn.setIcon(icon)
        self.gainBtn.setIconSize(QtCore.QSize(24, 24))
        self.gainBtn.setObjectName("gainBtn")
        self.gainCogLayout.addWidget(self.gainBtn)
        self.gainStacked.addWidget(self.gainCog)
        self.gainOkCancel = QtWidgets.QWidget()
        self.gainOkCancel.setObjectName("gainOkCancel")
        self.gainOkCancelLayout = QtWidgets.QHBoxLayout(self.gainOkCancel)
        self.gainOkCancelLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gainOkCancelLayout.setContentsMargins(0, 0, 0, 0)
        self.gainOkCancelLayout.setSpacing(0)
        self.gainOkCancelLayout.setObjectName("gainOkCancelLayout")
        self.gainOkBtn = QtWidgets.QPushButton(self.gainOkCancel)
        self.gainOkBtn.setText("")
        self.gainOkBtn.setIcon(icon1)
        self.gainOkBtn.setObjectName("gainOkBtn")
        self.gainOkCancelLayout.addWidget(self.gainOkBtn)
        self.gainCancelBtn = QtWidgets.QPushButton(self.gainOkCancel)
        self.gainCancelBtn.setText("")
        self.gainCancelBtn.setIcon(icon2)
        self.gainCancelBtn.setObjectName("gainCancelBtn")
        self.gainOkCancelLayout.addWidget(self.gainCancelBtn)
        self.gainStacked.addWidget(self.gainOkCancel)
        self.gainLayout.addWidget(self.gainStacked)
        self.receiverLayout.addLayout(self.gainLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.receiverLayout.addItem(spacerItem3)
        self.receiverLayout.setStretch(3, 1)
        self.leftLayout.addLayout(self.receiverLayout)
        self.scanResultLayout = QtWidgets.QVBoxLayout()
        self.scanResultLayout.setContentsMargins(-1, -1, -1, 15)
        self.scanResultLayout.setObjectName("scanResultLayout")
        self.line = QtWidgets.QFrame(self.leftFrame)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.scanResultLayout.addWidget(self.line)
        self.directionLayout = QtWidgets.QHBoxLayout()
        self.directionLayout.setContentsMargins(-1, -1, 5, -1)
        self.directionLayout.setObjectName("directionLayout")
        self.directionLbl = QtWidgets.QLabel(self.leftFrame)
        self.directionLbl.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.directionLbl.setFont(font)
        self.directionLbl.setObjectName("directionLbl")
        self.directionLayout.addWidget(self.directionLbl)
        self.directionVal = QtWidgets.QLabel(self.leftFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.directionVal.setFont(font)
        self.directionVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.directionVal.setObjectName("directionVal")
        self.directionLayout.addWidget(self.directionVal)
        self.directionLayout.setStretch(1, 1)
        self.scanResultLayout.addLayout(self.directionLayout)
        self.magnitudeLayout = QtWidgets.QHBoxLayout()
        self.magnitudeLayout.setContentsMargins(-1, -1, 5, -1)
        self.magnitudeLayout.setObjectName("magnitudeLayout")
        self.magnitudeLbl = QtWidgets.QLabel(self.leftFrame)
        self.magnitudeLbl.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.magnitudeLbl.setFont(font)
        self.magnitudeLbl.setObjectName("magnitudeLbl")
        self.magnitudeLayout.addWidget(self.magnitudeLbl)
        self.magnitudeVal = QtWidgets.QLabel(self.leftFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.magnitudeVal.setFont(font)
        self.magnitudeVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.magnitudeVal.setObjectName("magnitudeVal")
        self.magnitudeLayout.addWidget(self.magnitudeVal)
        self.magnitudeLayout.setStretch(1, 1)
        self.scanResultLayout.addLayout(self.magnitudeLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.scanResultLayout.addItem(spacerItem4)
        self.leftLayout.addLayout(self.scanResultLayout)
        self.leftLayout.setStretch(0, 1)
        self.leftLayout.setStretch(1, 1)
        self.gridLayout.addWidget(self.leftFrame, 0, 0, 1, 1)
        self.waterfallFrame = QtWidgets.QFrame(self.centralwidget)
        self.waterfallFrame.setMaximumSize(QtCore.QSize(400, 16777215))
        self.waterfallFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.waterfallFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.waterfallFrame.setObjectName("waterfallFrame")
        self.waterfallFrameLayout = QtWidgets.QGridLayout(self.waterfallFrame)
        self.waterfallFrameLayout.setContentsMargins(4, 4, 4, 4)
        self.waterfallFrameLayout.setObjectName("waterfallFrameLayout")
        self.waterfallToolbar = QtWidgets.QHBoxLayout()
        self.waterfallToolbar.setContentsMargins(4, -1, 4, 0)
        self.waterfallToolbar.setObjectName("waterfallToolbar")
        self.audioLayout = QtWidgets.QHBoxLayout()
        self.audioLayout.setObjectName("audioLayout")
        self.pauseBtn = QtWidgets.QPushButton(self.waterfallFrame)
        self.pauseBtn.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.pauseBtn.setFont(font)
        self.pauseBtn.setObjectName("pauseBtn")
        self.audioLayout.addWidget(self.pauseBtn)
        self.soundSlider = QtWidgets.QSlider(self.waterfallFrame)
        self.soundSlider.setMaximum(100)
        self.soundSlider.setOrientation(QtCore.Qt.Horizontal)
        self.soundSlider.setObjectName("soundSlider")
        self.audioLayout.addWidget(self.soundSlider)
        self.audioLayout.setStretch(0, 1)
        self.audioLayout.setStretch(1, 2)
        self.waterfallToolbar.addLayout(self.audioLayout)
        self.waterfallFrameLayout.addLayout(self.waterfallToolbar, 3, 0, 1, 1)
        self.waterfallHLine = QtWidgets.QFrame(self.waterfallFrame)
        self.waterfallHLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.waterfallHLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.waterfallHLine.setObjectName("waterfallHLine")
        self.waterfallFrameLayout.addWidget(self.waterfallHLine, 2, 0, 1, 1)
        self.waterfall = QtWidgets.QWidget(self.waterfallFrame)
        self.waterfall.setObjectName("waterfall")
        self.waterfallFrameLayout.addWidget(self.waterfall, 1, 0, 1, 1)
        self.connStatusLayout = QtWidgets.QHBoxLayout()
        self.connStatusLayout.setContentsMargins(0, 0, -1, 0)
        self.connStatusLayout.setObjectName("connStatusLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.connStatusLayout.addItem(spacerItem5)
        self.connStatusBtn = QtWidgets.QPushButton(self.waterfallFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connStatusBtn.sizePolicy().hasHeightForWidth())
        self.connStatusBtn.setSizePolicy(sizePolicy)
        self.connStatusBtn.setMinimumSize(QtCore.QSize(33, 33))
        self.connStatusBtn.setMaximumSize(QtCore.QSize(33, 33))
        self.connStatusBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Assets/Icons/connected"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connStatusBtn.setIcon(icon3)
        self.connStatusBtn.setIconSize(QtCore.QSize(30, 30))
        self.connStatusBtn.setObjectName("connStatusBtn")
        self.connStatusLayout.addWidget(self.connStatusBtn)
        self.waterfallFrameLayout.addLayout(self.connStatusLayout, 0, 0, 1, 1)
        self.waterfallFrameLayout.setRowStretch(1, 10)
        self.gridLayout.addWidget(self.waterfallFrame, 0, 4, 1, 1)
        self.centerLayout = QtWidgets.QGridLayout()
        self.centerLayout.setObjectName("centerLayout")
        self.scanStartLayout = QtWidgets.QHBoxLayout()
        self.scanStartLayout.setContentsMargins(-1, -1, -1, 0)
        self.scanStartLayout.setObjectName("scanStartLayout")
        self.scanButton = QtWidgets.QPushButton(self.centralwidget)
        self.scanButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.scanButton.setFont(font)
        self.scanButton.setObjectName("scanButton")
        self.scanStartLayout.addWidget(self.scanButton)
        self.centerLayout.addLayout(self.scanStartLayout, 4, 0, 1, 1)
        self.timeDispLayout = QtWidgets.QHBoxLayout()
        self.timeDispLayout.setObjectName("timeDispLayout")
        self.countdownLayout = QtWidgets.QGridLayout()
        self.countdownLayout.setObjectName("countdownLayout")
        self.countdownLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.countdownLbl.setFont(font)
        self.countdownLbl.setObjectName("countdownLbl")
        self.countdownLayout.addWidget(self.countdownLbl, 0, 0, 1, 1)
        self.countdownVal = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.countdownVal.setFont(font)
        self.countdownVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.countdownVal.setObjectName("countdownVal")
        self.countdownLayout.addWidget(self.countdownVal, 0, 1, 1, 1)
        self.timeDispLayout.addLayout(self.countdownLayout)
        self.scanTimeVLine = QtWidgets.QFrame(self.centralwidget)
        self.scanTimeVLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.scanTimeVLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scanTimeVLine.setObjectName("scanTimeVLine")
        self.timeDispLayout.addWidget(self.scanTimeVLine)
        self.scanTimeLayout = QtWidgets.QGridLayout()
        self.scanTimeLayout.setObjectName("scanTimeLayout")
        self.scanTimeLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.scanTimeLbl.setFont(font)
        self.scanTimeLbl.setObjectName("scanTimeLbl")
        self.scanTimeLayout.addWidget(self.scanTimeLbl, 0, 0, 1, 1)
        self.scanTimeVal = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.scanTimeVal.setFont(font)
        self.scanTimeVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scanTimeVal.setObjectName("scanTimeVal")
        self.scanTimeLayout.addWidget(self.scanTimeVal, 0, 1, 1, 1)
        self.timeDispLayout.addLayout(self.scanTimeLayout)
        self.centerLayout.addLayout(self.timeDispLayout, 3, 0, 1, 1)
        self.compassHLine = QtWidgets.QFrame(self.centralwidget)
        self.compassHLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.compassHLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.compassHLine.setObjectName("compassHLine")
        self.centerLayout.addWidget(self.compassHLine, 2, 0, 1, 1)
        self.compass = QtWidgets.QFrame(self.centralwidget)
        self.compass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.compass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.compass.setObjectName("compass")
        self.centerLayout.addWidget(self.compass, 1, 0, 1, 1)
        self.uavStatusLayout = QtWidgets.QHBoxLayout()
        self.uavStatusLayout.setObjectName("uavStatusLayout")
        self.altitudeLayout = QtWidgets.QGridLayout()
        self.altitudeLayout.setObjectName("altitudeLayout")
        self.altitudeLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.altitudeLbl.setFont(font)
        self.altitudeLbl.setObjectName("altitudeLbl")
        self.altitudeLayout.addWidget(self.altitudeLbl, 0, 0, 1, 1)
        self.altitudeVal = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.altitudeVal.setFont(font)
        self.altitudeVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.altitudeVal.setObjectName("altitudeVal")
        self.altitudeLayout.addWidget(self.altitudeVal, 0, 1, 1, 1)
        self.uavStatusLayout.addLayout(self.altitudeLayout)
        self.uavStatusVLine = QtWidgets.QFrame(self.centralwidget)
        self.uavStatusVLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.uavStatusVLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.uavStatusVLine.setObjectName("uavStatusVLine")
        self.uavStatusLayout.addWidget(self.uavStatusVLine)
        self.headingLayout = QtWidgets.QGridLayout()
        self.headingLayout.setObjectName("headingLayout")
        self.headingLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.headingLbl.setFont(font)
        self.headingLbl.setObjectName("headingLbl")
        self.headingLayout.addWidget(self.headingLbl, 0, 0, 1, 1)
        self.headingVal = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.headingVal.setFont(font)
        self.headingVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.headingVal.setObjectName("headingVal")
        self.headingLayout.addWidget(self.headingVal, 0, 1, 1, 1)
        self.uavStatusLayout.addLayout(self.headingLayout)
        self.centerLayout.addLayout(self.uavStatusLayout, 0, 0, 1, 1)
        self.centerLayout.setRowStretch(1, 20)
        self.gridLayout.addLayout(self.centerLayout, 0, 2, 1, 1)
        self.leftVLine = QtWidgets.QFrame(self.centralwidget)
        self.leftVLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.leftVLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.leftVLine.setObjectName("leftVLine")
        self.gridLayout.addWidget(self.leftVLine, 0, 1, 1, 1)
        self.rightVLine = QtWidgets.QFrame(self.centralwidget)
        self.rightVLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.rightVLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rightVLine.setObjectName("rightVLine")
        self.gridLayout.addWidget(self.rightVLine, 0, 3, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setColumnStretch(4, 1)
        self.centralWidgetLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1224, 28))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actionScan_Settings = QtWidgets.QAction(MainWindow)
        self.actionScan_Settings.setObjectName("actionScan_Settings")
        self.actionTelemetry = QtWidgets.QAction(MainWindow)
        self.actionTelemetry.setObjectName("actionTelemetry")
        self.menuSettings.addAction(self.actionTelemetry)
        self.menuSettings.addAction(self.actionScan_Settings)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.freqStacked.setCurrentIndex(0)
        self.snrStacked.setCurrentIndex(0)
        self.gainStacked.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZRC - Portable Aerial Radio Receiver"))
        self.freqLbl.setText(_translate("MainWindow", "Frequency"))
        self.freqVal.setText(_translate("MainWindow", "150.235"))
        self.freqUnit.setText(_translate("MainWindow", "MHz"))
        self.snrLbl.setText(_translate("MainWindow", "SNR Threshold"))
        self.gainLbl.setText(_translate("MainWindow", "Gain"))
        self.gainUnit.setText(_translate("MainWindow", "dB"))
        self.directionLbl.setText(_translate("MainWindow", "Direction"))
        self.directionVal.setText(_translate("MainWindow", "W | 95.6"))
        self.magnitudeLbl.setText(_translate("MainWindow", "Magnitue"))
        self.magnitudeVal.setText(_translate("MainWindow", "15.0"))
        self.pauseBtn.setText(_translate("MainWindow", "Pause"))
        self.scanButton.setText(_translate("MainWindow", "Scan"))
        self.countdownLbl.setText(_translate("MainWindow", "Countdown"))
        self.countdownVal.setText(_translate("MainWindow", "5"))
        self.scanTimeLbl.setText(_translate("MainWindow", "Scan Time"))
        self.scanTimeVal.setText(_translate("MainWindow", "45"))
        self.altitudeLbl.setText(_translate("MainWindow", "Altitude"))
        self.altitudeVal.setText(_translate("MainWindow", "5"))
        self.headingLbl.setText(_translate("MainWindow", "Heading"))
        self.headingVal.setText(_translate("MainWindow", "45"))
        self.menuSettings.setTitle(_translate("MainWindow", "ZARR"))
        self.actionScan_Settings.setText(_translate("MainWindow", "Scan Settings"))
        self.actionTelemetry.setText(_translate("MainWindow", "Telemetry"))

import resources
